FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app
EXPOSE 8085

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY . /app
RUN dotnet tool restore
RUN dotnet paket install
RUN dotnet paket restore

FROM build AS publish
RUN dotnet fake run build.fsx -t "Build"

FROM base AS final
WORKDIR /app
CMD ["./src/Server/out/Server"]